kind: Service
apiVersion: v1
metadata:
  name:  mysql-service
spec:
  selector:
    app: mysql-server
    tier: db
  type:  LoadBalancer
  ports:
  - name:  mysql-port
    port:  3306
    targetPort:  3306