substitutions:
  _FIRSTGOWEB_VERSION: 0.0.1

steps:
  - id: "Efetuando testes unitários"
    name: gcr.io/cloud-builders/go
    args: ["test", "./goweb/src/main/"]
    env:
      - "GOPATH=."
  - id: "Gerando o container"
    name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/codeeducation-hirao/firstgoweb:${_FIRSTGOWEB_VERSION}", "-t", "gcr.io/codeeducation-hirao/firstgoweb:latest", "./goweb/"]
images:
  - 'gcr.io/$PROJECT_ID/firstgoweb:latest'
  - 'gcr.io/$PROJECT_ID/firstgoweb:${_FIRSTGOWEB_VERSION}'